### ISSUE TITLE
allow get_all queries to accept multiple primary keys

### ISSUE THREAD

**Issue by kylewhite21** [republicwireless-open/rethink-erlang#5]
Queries where I provide multiple (a list) of keys to `get_all` return no objects when there should be results for every key provided. Example query below (running Elixir, so excuse the syntax).

```
qry = :reql.new()
|> :reql.db("my_db")
|> :reql.table("my_table")
|> :reql.get_all(["pk1", "pk2"], %{index: "my_index"})
```

**Comment by jessestimpson** [comment]
PR #6 adds support for this, but since we can't support variable length args, you'll have to wrap your args with `reql:args/1`

For Erlang, you can reference the new unit test.

In Elixir it looks like this:
```
 |> :reql.get_all(:reql.args(["thing1","thing2"]), %{index: "ind"})
```
